export type MatchPlayer = {
  id: number;
  name: string;
  age: number;
  location: string;
  skill: string;
  availability: string;
  purpose: string;
  tags: string[];
  photo: string | null;
  gamesPlayed: number;
  matchScore: number;
  matchReasons: string[];
};

export const sportPlayerMap: Record<string, number[]> = {
  tennis: [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116],
  badminton: [201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216],
  pickleball: [301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313],
  bouldering: [401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413],
  golf: [501, 502, 503, 504, 505, 506, 507, 508],
  running: [601, 602, 603, 604, 605, 606, 607],
};

export const DUMMY_PLAYERS: MatchPlayer[] = [
  // Tennis 101-108
  {
    id: 101,
    name: "Alex J.",
    age: 28,
    location: "Jersey City, NJ",
    skill: "3.5 (Intermediate)",
    availability: "Weekends/Eves",
    purpose: "Trying to level up 🏆",
    tags: ["Low-key competitive", "Won't flake"],
    photo: null,
    gamesPlayed: 12,
    matchScore: 92,
    matchReasons: ["🕐 Schedule match", "🎯 Same level", "📍 Nearby"],
  },
  {
    id: 102,
    name: "Sarah M.",
    age: 31,
    location: "Manhattan, NY",
    skill: "3.0 (Advanced Beginner)",
    availability: "Weekday Eves",
    purpose: "Looking for my go-to partner 🤝",
    tags: ["Chill vibes only", "Good banter"],
    photo: null,
    gamesPlayed: 8,
    matchScore: 78,
    matchReasons: ["🎯 Same level", "💪 Same goal"],
  },
  {
    id: 103,
    name: "Maria L.",
    age: 26,
    location: "Hoboken, NJ",
    skill: "4.0 (Intermediate+)",
    availability: "Weekends",
    purpose: "Just here to meet people 😎",
    tags: ["Social cardio", "Shows up"],
    photo: null,
    gamesPlayed: 21,
    matchScore: 85,
    matchReasons: ["🕐 Schedule match", "📍 Nearby"],
  },
  {
    id: 104,
    name: "James K.",
    age: 33,
    location: "Brooklyn, NY",
    skill: "2.5 (Beginner+)",
    availability: "Mornings",
    purpose: "Just trying to stay active 🏃",
    tags: ["Beginner-friendly", "No pressure"],
    photo: null,
    gamesPlayed: 5,
    matchScore: 71,
    matchReasons: ["💪 Same goal", "🎯 Same level"],
  },
  {
    id: 105,
    name: "Lisa C.",
    age: 29,
    location: "Queens, NY",
    skill: "3.5 (Intermediate)",
    availability: "Flexible",
    purpose: "Trying to level up 🏆",
    tags: ["Down for a challenge", "Chatty", "Won't flake"],
    photo: null,
    gamesPlayed: 17,
    matchScore: 88,
    matchReasons: ["🕐 Schedule match", "🎯 Same level", "💪 Same goal"],
  },
  {
    id: 106,
    name: "David W.",
    age: 35,
    location: "Weehawken, NJ",
    skill: "4.5 (Advanced)",
    availability: "Weekends",
    purpose: "Looking for my go-to partner 🤝",
    tags: ["Low-key competitive", "Shows up"],
    photo: null,
    gamesPlayed: 34,
    matchScore: 65,
    matchReasons: ["📍 Nearby"],
  },
  {
    id: 107,
    name: "Emma R.",
    age: 24,
    location: "Union City, NJ",
    skill: "2.0 (Beginner)",
    availability: "Evenings",
    purpose: "Just here to meet people 😎",
    tags: ["Chill vibes only", "Beginner-friendly"],
    photo: null,
    gamesPlayed: 3,
    matchScore: 76,
    matchReasons: ["🕐 Schedule match", "💪 Same goal"],
  },
  {
    id: 108,
    name: "Chris T.",
    age: 30,
    location: "Fort Lee, NJ",
    skill: "3.0 (Advanced Beginner)",
    availability: "Weekends/Eves",
    purpose: "Other ✨",
    tags: ["Good banter", "No pressure", "Social cardio"],
    photo: null,
    gamesPlayed: 9,
    matchScore: 83,
    matchReasons: ["🎯 Same level", "📍 Nearby", "💪 Same goal"],
  },
  // Tennis 109-116
  {
    id: 109,
    name: "Mia R.",
    age: 24,
    location: "Upper East Side, NY",
    skill: "3.0 (Advanced Beginner)",
    availability: "Weekends",
    purpose: "Just here to vibe 😎",
    tags: ["Chill vibes", "Flexible"],
    photo: null,
    gamesPlayed: 7,
    matchScore: 76,
    matchReasons: ["📍 Nearby", "💪 Same goal"],
  },
  {
    id: 110,
    name: "Derek W.",
    age: 36,
    location: "Astoria, NY",
    skill: "4.5 (Advanced)",
    availability: "Weekday Eves",
    purpose: "Trying to level up 🏆",
    tags: ["Serious", "Competitive"],
    photo: null,
    gamesPlayed: 41,
    matchScore: 83,
    matchReasons: ["🎯 Same level", "🕐 Schedule match"],
  },
  {
    id: 111,
    name: "Priya S.",
    age: 28,
    location: "Jersey City, NJ",
    skill: "3.5 (Intermediate)",
    availability: "Weekends/Eves",
    purpose: "Looking for my go-to partner 🤝",
    tags: ["Reliable", "Fun"],
    photo: null,
    gamesPlayed: 16,
    matchScore: 87,
    matchReasons: ["🕐 Schedule match", "📍 Nearby", "🎯 Same level"],
  },
  {
    id: 112,
    name: "Jake O.",
    age: 31,
    location: "Manhattan, NY",
    skill: "2.5 (Beginner+)",
    availability: "Weekday Mornings",
    purpose: "Keeping it moving 🏃",
    tags: ["Early bird", "Consistent"],
    photo: null,
    gamesPlayed: 9,
    matchScore: 72,
    matchReasons: ["💪 Same goal"],
  },
  {
    id: 113,
    name: "Sophia T.",
    age: 27,
    location: "Brooklyn, NY",
    skill: "3.0 (Advanced Beginner)",
    availability: "Weekends",
    purpose: "Just here to vibe 😎",
    tags: ["Chill", "No pressure"],
    photo: null,
    gamesPlayed: 11,
    matchScore: 78,
    matchReasons: ["📍 Nearby", "💪 Same goal"],
  },
  {
    id: 114,
    name: "Marcus H.",
    age: 34,
    location: "Hoboken, NJ",
    skill: "4.0 (Intermediate+)",
    availability: "Weekday Eves",
    purpose: "Trying to level up 🏆",
    tags: ["Competitive", "Won't flake"],
    photo: null,
    gamesPlayed: 29,
    matchScore: 84,
    matchReasons: ["🎯 Same level", "🕐 Schedule match", "📍 Nearby"],
  },
  {
    id: 115,
    name: "Lily C.",
    age: 22,
    location: "Manhattan, NY",
    skill: "3.5 (Intermediate)",
    availability: "Weekends/Eves",
    purpose: "Looking for my go-to partner 🤝",
    tags: ["Fun", "Consistent"],
    photo: null,
    gamesPlayed: 5,
    matchScore: 80,
    matchReasons: ["🕐 Schedule match", "🎯 Same level"],
  },
  {
    id: 116,
    name: "Victor N.",
    age: 39,
    location: "Jersey City, NJ",
    skill: "3.0 (Advanced Beginner)",
    availability: "Weekday Mornings",
    purpose: "Keeping it moving 🏃",
    tags: ["Early bird", "Reliable"],
    photo: null,
    gamesPlayed: 33,
    matchScore: 75,
    matchReasons: ["📍 Nearby", "💪 Same goal"],
  },
  // Badminton 201-208
  {
    id: 201,
    name: "Ryan C.",
    age: 27,
    location: "Flushing, NY",
    skill: "Intermediate (C-B)",
    availability: "Weekends",
    purpose: "Trying to level up 🏆",
    tags: ["Motivated", "Consistent"],
    photo: null,
    gamesPlayed: 22,
    matchScore: 89,
    matchReasons: ["📍 Nearby", "🎯 Same level", "🕐 Schedule match"],
  },
  {
    id: 202,
    name: "Nina P.",
    age: 29,
    location: "Manhattan, NY",
    skill: "Advanced (B-A)",
    availability: "Weekday Eves",
    purpose: "Looking for my go-to partner 🤝",
    tags: ["Competitive", "Reliable"],
    photo: null,
    gamesPlayed: 38,
    matchScore: 82,
    matchReasons: ["🎯 Same level", "💪 Same goal"],
  },
  {
    id: 203,
    name: "Kenji M.",
    age: 24,
    location: "Brooklyn, NY",
    skill: "Beginner (D-C)",
    availability: "Weekends/Eves",
    purpose: "Just here to vibe 😎",
    tags: ["Chill", "Encouraging"],
    photo: null,
    gamesPlayed: 6,
    matchScore: 74,
    matchReasons: ["💪 Same goal", "📍 Nearby"],
  },
  {
    id: 204,
    name: "Alison B.",
    age: 32,
    location: "Jersey City, NJ",
    skill: "Intermediate (C-B)",
    availability: "Weekday Mornings",
    purpose: "Keeping it moving 🏃",
    tags: ["Early bird", "Won't flake"],
    photo: null,
    gamesPlayed: 15,
    matchScore: 79,
    matchReasons: ["🕐 Schedule match", "📍 Nearby"],
  },
  {
    id: 205,
    name: "Dev P.",
    age: 26,
    location: "Astoria, NY",
    skill: "Advanced (B-A)",
    availability: "Weekends",
    purpose: "Trying to level up 🏆",
    tags: ["Serious", "Competitive"],
    photo: null,
    gamesPlayed: 47,
    matchScore: 85,
    matchReasons: ["🎯 Same level", "🕐 Schedule match", "💪 Same goal"],
  },
  {
    id: 206,
    name: "Chloe W.",
    age: 23,
    location: "Flushing, NY",
    skill: "Beginner (D-C)",
    availability: "Weekends",
    purpose: "Looking for my go-to partner 🤝",
    tags: ["Fun", "Flexible"],
    photo: null,
    gamesPlayed: 4,
    matchScore: 70,
    matchReasons: ["📍 Nearby"],
  },
  {
    id: 207,
    name: "Marcus L.",
    age: 35,
    location: "Hoboken, NJ",
    skill: "Intermediate (C-B)",
    availability: "Weekday Eves",
    purpose: "Just here to vibe 😎",
    tags: ["Chill vibes", "Good banter"],
    photo: null,
    gamesPlayed: 28,
    matchScore: 81,
    matchReasons: ["🎯 Same level", "📍 Nearby"],
  },
  {
    id: 208,
    name: "Yuki T.",
    age: 28,
    location: "Manhattan, NY",
    skill: "Intermediate (C-B)",
    availability: "Weekends/Eves",
    purpose: "Keeping it moving 🏃",
    tags: ["Consistent", "Reliable"],
    photo: null,
    gamesPlayed: 19,
    matchScore: 77,
    matchReasons: ["🕐 Schedule match", "💪 Same goal"],
  },
  // Badminton 209-216
  {
    id: 209,
    name: "Iris L.",
    age: 23,
    location: "Flushing, NY",
    skill: "Intermediate (C-B)",
    availability: "Weekends",
    purpose: "Trying to level up 🏆",
    tags: ["Motivated", "Consistent"],
    photo: null,
    gamesPlayed: 19,
    matchScore: 86,
    matchReasons: ["📍 Nearby", "🎯 Same level", "💪 Same goal"],
  },
  {
    id: 210,
    name: "Tom K.",
    age: 30,
    location: "Manhattan, NY",
    skill: "Advanced (B-A)",
    availability: "Weekday Eves",
    purpose: "Just here to vibe 😎",
    tags: ["Chill", "Good banter"],
    photo: null,
    gamesPlayed: 52,
    matchScore: 79,
    matchReasons: ["🎯 Same level", "🕐 Schedule match"],
  },
  {
    id: 211,
    name: "Grace Y.",
    age: 26,
    location: "Flushing, NY",
    skill: "Beginner (D-C)",
    availability: "Weekends/Eves",
    purpose: "Looking for my go-to partner 🤝",
    tags: ["Flexible", "Fun"],
    photo: null,
    gamesPlayed: 8,
    matchScore: 82,
    matchReasons: ["📍 Nearby", "💪 Same goal"],
  },
  {
    id: 212,
    name: "Nathan P.",
    age: 28,
    location: "Brooklyn, NY",
    skill: "Intermediate (C-B)",
    availability: "Weekday Mornings",
    purpose: "Keeping it moving 🏃",
    tags: ["Early bird", "Won't flake"],
    photo: null,
    gamesPlayed: 24,
    matchScore: 77,
    matchReasons: ["🎯 Same level", "💪 Same goal"],
  },
  {
    id: 213,
    name: "Wendy C.",
    age: 31,
    location: "Astoria, NY",
    skill: "Intermediate (C-B)",
    availability: "Weekends",
    purpose: "Just here to vibe 😎",
    tags: ["Chill vibes", "Reliable"],
    photo: null,
    gamesPlayed: 14,
    matchScore: 84,
    matchReasons: ["🕐 Schedule match", "📍 Nearby"],
  },
  {
    id: 214,
    name: "Oscar M.",
    age: 27,
    location: "Jersey City, NJ",
    skill: "Advanced (B-A)",
    availability: "Weekday Eves",
    purpose: "Trying to level up 🏆",
    tags: ["Serious", "Competitive"],
    photo: null,
    gamesPlayed: 43,
    matchScore: 81,
    matchReasons: ["🎯 Same level", "📍 Nearby"],
  },
  {
    id: 215,
    name: "Fiona T.",
    age: 25,
    location: "Manhattan, NY",
    skill: "Beginner (D-C)",
    availability: "Weekends/Eves",
    purpose: "Looking for my go-to partner 🤝",
    tags: ["Encouraging", "Fun"],
    photo: null,
    gamesPlayed: 6,
    matchScore: 73,
    matchReasons: ["💪 Same goal"],
  },
  {
    id: 216,
    name: "Leo W.",
    age: 33,
    location: "Hoboken, NJ",
    skill: "Intermediate (C-B)",
    availability: "Weekday Mornings",
    purpose: "Keeping it moving 🏃",
    tags: ["Early bird", "Consistent"],
    photo: null,
    gamesPlayed: 31,
    matchScore: 78,
    matchReasons: ["📍 Nearby", "🎯 Same level"],
  },
  // Pickleball 301-308
  {
    id: 301,
    name: "Carlos M.",
    age: 31,
    location: "Hoboken, NJ",
    skill: "3.5 (Intermediate)",
    availability: "Weekends",
    purpose: "Trying to level up 🏆",
    tags: ["Competitive", "Reliable"],
    photo: null,
    gamesPlayed: 27,
    matchScore: 90,
    matchReasons: ["🕐 Schedule match", "🎯 Same level", "📍 Nearby"],
  },
  {
    id: 302,
    name: "Jenny H.",
    age: 28,
    location: "Brooklyn, NY",
    skill: "3.0 (Advanced Beginner)",
    availability: "Weekday Eves",
    purpose: "Just here to vibe 😎",
    tags: ["Chill", "Fun"],
    photo: null,
    gamesPlayed: 12,
    matchScore: 79,
    matchReasons: ["💪 Same goal", "📍 Nearby"],
  },
  {
    id: 303,
    name: "Mike D.",
    age: 34,
    location: "Jersey City, NJ",
    skill: "4.0 (Advanced Intermediate)",
    availability: "Weekends/Eves",
    purpose: "Looking for my go-to partner 🤝",
    tags: ["Won't flake", "Consistent"],
    photo: null,
    gamesPlayed: 35,
    matchScore: 86,
    matchReasons: ["🎯 Same level", "🕐 Schedule match"],
  },
  {
    id: 304,
    name: "Tina S.",
    age: 26,
    location: "Astoria, NY",
    skill: "2.5 (Beginner)",
    availability: "Weekends",
    purpose: "Keeping it moving 🏃",
    tags: ["Beginner-friendly", "Encouraging"],
    photo: null,
    gamesPlayed: 5,
    matchScore: 68,
    matchReasons: ["💪 Same goal"],
  },
  {
    id: 305,
    name: "Brian F.",
    age: 38,
    location: "Manhattan, NY",
    skill: "4.5 (Advanced)",
    availability: "Weekday Mornings",
    purpose: "Trying to level up 🏆",
    tags: ["Serious", "Early bird"],
    photo: null,
    gamesPlayed: 44,
    matchScore: 83,
    matchReasons: ["🎯 Same level", "🕐 Schedule match", "📍 Nearby"],
  },
  {
    id: 306,
    name: "Kate R.",
    age: 29,
    location: "Queens, NY",
    skill: "3.5 (Intermediate)",
    availability: "Flexible",
    purpose: "Just here to vibe 😎",
    tags: ["Chill vibes", "Flexible"],
    photo: null,
    gamesPlayed: 18,
    matchScore: 81,
    matchReasons: ["📍 Nearby", "💪 Same goal"],
  },
  {
    id: 307,
    name: "Steve L.",
    age: 42,
    location: "Fort Lee, NJ",
    skill: "3.0 (Recreational)",
    availability: "Weekends/Eves",
    purpose: "Looking for my go-to partner 🤝",
    tags: ["Reliable", "Good banter"],
    photo: null,
    gamesPlayed: 22,
    matchScore: 75,
    matchReasons: ["🕐 Schedule match", "📍 Nearby"],
  },
  {
    id: 308,
    name: "Amy Z.",
    age: 33,
    location: "Weehawken, NJ",
    skill: "4.0 (Advanced Intermediate)",
    availability: "Weekday Eves",
    purpose: "Trying to level up 🏆",
    tags: ["Motivated", "Competitive"],
    photo: null,
    gamesPlayed: 30,
    matchScore: 87,
    matchReasons: ["🎯 Same level", "💪 Same goal", "📍 Nearby"],
  },
  // Pickleball 309-313
  {
    id: 309,
    name: "Amber S.",
    age: 36,
    location: "Manhattan, NY",
    skill: "4.5 (Expert)",
    availability: "Weekday Mornings",
    purpose: "Trying to level up 🏆",
    tags: ["Serious", "Competitive"],
    photo: null,
    gamesPlayed: 67,
    matchScore: 84,
    matchReasons: ["🎯 Same level", "🕐 Schedule match"],
  },
  {
    id: 310,
    name: "Josh T.",
    age: 29,
    location: "Brooklyn, NY",
    skill: "3.0 (Recreational)",
    availability: "Weekends/Eves",
    purpose: "Just here to vibe 😎",
    tags: ["Chill", "Flexible"],
    photo: null,
    gamesPlayed: 16,
    matchScore: 77,
    matchReasons: ["📍 Nearby", "💪 Same goal"],
  },
  {
    id: 311,
    name: "Rosa M.",
    age: 44,
    location: "Jersey City, NJ",
    skill: "3.5 (Intermediate)",
    availability: "Weekends",
    purpose: "Looking for my go-to partner 🤝",
    tags: ["Reliable", "Consistent"],
    photo: null,
    gamesPlayed: 41,
    matchScore: 85,
    matchReasons: ["🕐 Schedule match", "📍 Nearby", "💪 Same goal"],
  },
  {
    id: 312,
    name: "Ian K.",
    age: 32,
    location: "Hoboken, NJ",
    skill: "2.5 (Beginner)",
    availability: "Weekday Eves",
    purpose: "Keeping it moving 🏃",
    tags: ["Fun", "Won't flake"],
    photo: null,
    gamesPlayed: 9,
    matchScore: 72,
    matchReasons: ["📍 Nearby"],
  },
  {
    id: 313,
    name: "Vera L.",
    age: 27,
    location: "Astoria, NY",
    skill: "4.0 (Advanced)",
    availability: "Weekday Mornings",
    purpose: "Trying to level up 🏆",
    tags: ["Motivated", "Competitive"],
    photo: null,
    gamesPlayed: 28,
    matchScore: 88,
    matchReasons: ["🎯 Same level", "🕐 Schedule match", "💪 Same goal"],
  },
  // Bouldering 401-408
  {
    id: 401,
    name: "Alex T.",
    age: 24,
    location: "Brooklyn, NY",
    skill: "V2-V3 (Beginner+)",
    availability: "Weekends",
    purpose: "Just here to vibe 😎",
    tags: ["Chill", "Encouraging"],
    photo: null,
    gamesPlayed: 10,
    matchScore: 79,
    matchReasons: ["📍 Nearby", "💪 Same goal"],
  },
  {
    id: 402,
    name: "Jordan P.",
    age: 29,
    location: "Manhattan, NY",
    skill: "V3-V4 (Intermediate)",
    availability: "Weekday Eves",
    purpose: "Trying to level up 🏆",
    tags: ["Motivated", "Consistent"],
    photo: null,
    gamesPlayed: 32,
    matchScore: 86,
    matchReasons: ["🎯 Same level", "🕐 Schedule match"],
  },
  {
    id: 403,
    name: "Casey R.",
    age: 26,
    location: "Jersey City, NJ",
    skill: "V4-V5 (Intermediate+)",
    availability: "Weekends/Eves",
    purpose: "Looking for my go-to partner 🤝",
    tags: ["Reliable", "Won't flake"],
    photo: null,
    gamesPlayed: 21,
    matchScore: 83,
    matchReasons: ["📍 Nearby", "🎯 Same level", "💪 Same goal"],
  },
  {
    id: 404,
    name: "Riley M.",
    age: 22,
    location: "Astoria, NY",
    skill: "VB-V0 (Beginner)",
    availability: "Weekends",
    purpose: "Keeping it moving 🏃",
    tags: ["Beginner-friendly", "Fun"],
    photo: null,
    gamesPlayed: 4,
    matchScore: 69,
    matchReasons: ["💪 Same goal"],
  },
  {
    id: 405,
    name: "Taylor B.",
    age: 31,
    location: "Hoboken, NJ",
    skill: "V5-V6 (Advanced)",
    availability: "Weekday Mornings",
    purpose: "Trying to level up 🏆",
    tags: ["Serious", "Early bird"],
    photo: null,
    gamesPlayed: 55,
    matchScore: 81,
    matchReasons: ["🎯 Same level", "🕐 Schedule match"],
  },
  {
    id: 406,
    name: "Morgan S.",
    age: 27,
    location: "Brooklyn, NY",
    skill: "V3-V4 (Intermediate)",
    availability: "Weekday Eves",
    purpose: "Just here to vibe 😎",
    tags: ["Chill vibes", "Consistent"],
    photo: null,
    gamesPlayed: 17,
    matchScore: 78,
    matchReasons: ["📍 Nearby", "💪 Same goal"],
  },
  {
    id: 407,
    name: "Quinn D.",
    age: 33,
    location: "Manhattan, NY",
    skill: "V4-V5 (Intermediate+)",
    availability: "Weekends",
    purpose: "Looking for my go-to partner 🤝",
    tags: ["Reliable", "Competitive"],
    photo: null,
    gamesPlayed: 38,
    matchScore: 85,
    matchReasons: ["🕐 Schedule match", "🎯 Same level", "📍 Nearby"],
  },
  {
    id: 408,
    name: "Avery K.",
    age: 25,
    location: "Queens, NY",
    skill: "V2-V3 (Beginner+)",
    availability: "Weekends/Eves",
    purpose: "Keeping it moving 🏃",
    tags: ["Flexible", "Fun"],
    photo: null,
    gamesPlayed: 8,
    matchScore: 73,
    matchReasons: ["📍 Nearby"],
  },
  // Bouldering 409-413
  {
    id: 409,
    name: "Sam Y.",
    age: 23,
    location: "Manhattan, NY",
    skill: "V4-V5 (Intermediate+)",
    availability: "Weekday Eves",
    purpose: "Just here to vibe 😎",
    tags: ["Chill", "Encouraging"],
    photo: null,
    gamesPlayed: 18,
    matchScore: 82,
    matchReasons: ["🎯 Same level", "🕐 Schedule match"],
  },
  {
    id: 410,
    name: "Hana K.",
    age: 28,
    location: "Brooklyn, NY",
    skill: "V2-V3 (Beginner+)",
    availability: "Weekends",
    purpose: "Looking for my go-to partner 🤝",
    tags: ["Fun", "Reliable"],
    photo: null,
    gamesPlayed: 11,
    matchScore: 76,
    matchReasons: ["📍 Nearby", "💪 Same goal"],
  },
  {
    id: 411,
    name: "Felix R.",
    age: 30,
    location: "Jersey City, NJ",
    skill: "V3-V4 (Intermediate)",
    availability: "Weekends/Eves",
    purpose: "Trying to level up 🏆",
    tags: ["Motivated", "Won't flake"],
    photo: null,
    gamesPlayed: 26,
    matchScore: 87,
    matchReasons: ["🕐 Schedule match", "📍 Nearby", "💪 Same goal"],
  },
  {
    id: 412,
    name: "Nora W.",
    age: 25,
    location: "Manhattan, NY",
    skill: "V5-V6 (Advanced)",
    availability: "Weekday Mornings",
    purpose: "Keeping it moving 🏃",
    tags: ["Serious", "Early bird"],
    photo: null,
    gamesPlayed: 49,
    matchScore: 80,
    matchReasons: ["🎯 Same level", "🕐 Schedule match"],
  },
  {
    id: 413,
    name: "Dylan C.",
    age: 27,
    location: "Astoria, NY",
    skill: "V3-V4 (Intermediate)",
    availability: "Weekday Eves",
    purpose: "Just here to vibe 😎",
    tags: ["Chill vibes", "Consistent"],
    photo: null,
    gamesPlayed: 14,
    matchScore: 74,
    matchReasons: ["💪 Same goal"],
  },
  // Golf 501-508
  {
    id: 501,
    name: "Patrick H.",
    age: 42,
    location: "Westchester, NY",
    skill: "Intermediate (15.1–20.0)",
    availability: "Weekends",
    purpose: "Trying to level up 🏆",
    tags: ["Serious", "Consistent"],
    photo: null,
    gamesPlayed: 36,
    matchScore: 88,
    matchReasons: ["🕐 Schedule match", "🎯 Same level", "📍 Nearby"],
  },
  {
    id: 502,
    name: "Helen G.",
    age: 38,
    location: "Jersey City, NJ",
    skill: "Beginner (20.1–25.0)",
    availability: "Weekday Mornings",
    purpose: "Keeping it moving 🏃",
    tags: ["Early bird", "Reliable"],
    photo: null,
    gamesPlayed: 14,
    matchScore: 74,
    matchReasons: ["📍 Nearby", "💪 Same goal"],
  },
  {
    id: 503,
    name: "Robert K.",
    age: 45,
    location: "Manhattan, NY",
    skill: "Advanced (5.1–10.0)",
    availability: "Weekends/Eves",
    purpose: "Looking for my go-to partner 🤝",
    tags: ["Competitive", "Won't flake"],
    photo: null,
    gamesPlayed: 52,
    matchScore: 82,
    matchReasons: ["🎯 Same level", "🕐 Schedule match"],
  },
  {
    id: 504,
    name: "Susan L.",
    age: 33,
    location: "Brooklyn, NY",
    skill: "Upper Intermediate (10.1–15.0)",
    availability: "Weekends",
    purpose: "Just here to vibe 😎",
    tags: ["Chill", "Fun"],
    photo: null,
    gamesPlayed: 21,
    matchScore: 79,
    matchReasons: ["📍 Nearby", "💪 Same goal"],
  },
  {
    id: 505,
    name: "Michael T.",
    age: 50,
    location: "Fort Lee, NJ",
    skill: "Beginner+ (25.1–30.0)",
    availability: "Weekday Eves",
    purpose: "Trying to level up 🏆",
    tags: ["Motivated", "Encouraging"],
    photo: null,
    gamesPlayed: 8,
    matchScore: 71,
    matchReasons: ["💪 Same goal"],
  },
  {
    id: 506,
    name: "Laura B.",
    age: 29,
    location: "Hoboken, NJ",
    skill: "Intermediate (15.1–20.0)",
    availability: "Flexible",
    purpose: "Looking for my go-to partner 🤝",
    tags: ["Reliable", "Flexible"],
    photo: null,
    gamesPlayed: 19,
    matchScore: 85,
    matchReasons: ["🕐 Schedule match", "🎯 Same level", "📍 Nearby"],
  },
  {
    id: 507,
    name: "George W.",
    age: 55,
    location: "Queens, NY",
    skill: "High Handicap (30.1+)",
    availability: "Weekends",
    purpose: "Just here to vibe 😎",
    tags: ["Chill vibes", "No pressure"],
    photo: null,
    gamesPlayed: 6,
    matchScore: 66,
    matchReasons: ["📍 Nearby"],
  },
  {
    id: 508,
    name: "Diana C.",
    age: 41,
    location: "Weehawken, NJ",
    skill: "Upper Intermediate (10.1–15.0)",
    availability: "Weekday Mornings",
    purpose: "Keeping it moving 🏃",
    tags: ["Early bird", "Consistent"],
    photo: null,
    gamesPlayed: 27,
    matchScore: 80,
    matchReasons: ["🎯 Same level", "🕐 Schedule match"],
  },
  // Running 601-607
  {
    id: 601,
    name: "Jamie S.",
    age: 27,
    location: "Central Park, NY",
    skill: "9:00–10:29/mi - Steady",
    availability: "Weekday Mornings",
    purpose: "Keeping it moving 🏃",
    tags: ["Early bird", "Consistent"],
    photo: null,
    gamesPlayed: 45,
    matchScore: 89,
    matchReasons: ["🕐 Schedule match", "🎯 Same level", "💪 Same goal"],
  },
  {
    id: 602,
    name: "Olivia R.",
    age: 24,
    location: "Brooklyn, NY",
    skill: "10:30–11:59/mi - Easygoing",
    availability: "Weekends",
    purpose: "Just here to vibe 😎",
    tags: ["Chill", "Flexible"],
    photo: null,
    gamesPlayed: 12,
    matchScore: 76,
    matchReasons: ["📍 Nearby", "💪 Same goal"],
  },
  {
    id: 603,
    name: "Ethan M.",
    age: 32,
    location: "Jersey City, NJ",
    skill: "7:45–8:59/mi - Strong",
    availability: "Weekday Eves",
    purpose: "Trying to level up 🏆",
    tags: ["Motivated", "Competitive"],
    photo: null,
    gamesPlayed: 58,
    matchScore: 84,
    matchReasons: ["🎯 Same level", "🕐 Schedule match"],
  },
  {
    id: 604,
    name: "Hannah L.",
    age: 29,
    location: "Manhattan, NY",
    skill: "6:30–7:44/mi - Advanced",
    availability: "Weekday Mornings",
    purpose: "Looking for my go-to partner 🤝",
    tags: ["Serious", "Won't flake"],
    photo: null,
    gamesPlayed: 72,
    matchScore: 81,
    matchReasons: ["🎯 Same level", "📍 Nearby"],
  },
  {
    id: 605,
    name: "Noah P.",
    age: 26,
    location: "Astoria, NY",
    skill: "9:00–10:29/mi - Steady",
    availability: "Weekends/Eves",
    purpose: "Just here to vibe 😎",
    tags: ["Reliable", "Fun"],
    photo: null,
    gamesPlayed: 23,
    matchScore: 78,
    matchReasons: ["🕐 Schedule match", "💪 Same goal"],
  },
  {
    id: 606,
    name: "Zoe K.",
    age: 35,
    location: "Hoboken, NJ",
    skill: "12:00+/mi - Just getting started",
    availability: "Weekends",
    purpose: "Keeping it moving 🏃",
    tags: ["Beginner-friendly", "Encouraging"],
    photo: null,
    gamesPlayed: 5,
    matchScore: 70,
    matchReasons: ["💪 Same goal", "📍 Nearby"],
  },
  {
    id: 607,
    name: "Tyler B.",
    age: 30,
    location: "Brooklyn, NY",
    skill: "7:45–8:59/mi - Strong",
    availability: "Weekday Mornings",
    purpose: "Trying to level up 🏆",
    tags: ["Early bird", "Competitive"],
    photo: null,
    gamesPlayed: 41,
    matchScore: 86,
    matchReasons: ["🎯 Same level", "🕐 Schedule match", "📍 Nearby"],
  },
];

export function getSortedPlayersForSport(sportId: string): MatchPlayer[] {
  const ids = sportPlayerMap[sportId] ?? sportPlayerMap.tennis;
  const idSet = new Set(ids);
  return DUMMY_PLAYERS.filter((p) => idSet.has(p.id)).sort(
    (a, b) => b.matchScore - a.matchScore
  );
}
